/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pablocompany.practicano1lfp.frontend;

import com.pablocompany.practicano1lfp.backDefrontend.ColocarFondos;
import com.pablocompany.practicano1lfp.backend.ConfigException;
import com.pablocompany.practicano1lfp.backend.ErrorEncontradoException;
import com.pablocompany.practicano1lfp.backend.ErrorPuntualException;
import com.pablocompany.practicano1lfp.backend.LectorEntradas;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author pablo
 */
public class EditarConfiguracion extends javax.swing.JDialog {

    //Flag que se activa para determinar cuando se genera algun cambio en el config
    private boolean hayCambio;

    private LectorEntradas gestionLecturas;

    private JTextPane paneLogAnalisis;
    private JTextPane paneLogErrores;

    /**
     * Creates new form EditarConfiguracion
     */
    public EditarConfiguracion(java.awt.Frame parent, boolean modal, LectorEntradas gestorLecturas, JTextPane paneAnalisis, JTextPane paneLogError) {
        super(parent, modal);
        try {
            initComponents();

            this.setLocationRelativeTo(null);

            ColocarFondos pintarPanel = new ColocarFondos(this, this.panelPrincipal);

            pintarPanel.pintarDialog("/com/pablocompany/practicano1/target/images/overlay2.png");

            this.paneLogAnalisis = paneAnalisis;
            this.paneLogErrores = paneLogError;

            this.gestionLecturas = gestorLecturas;
            this.hayCambio = false;

            this.gestionLecturas.getDatosConfig().mostrarConfiguracion(this.textLogConfig);
        } catch (ErrorPuntualException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de interpretacion", JOptionPane.ERROR_MESSAGE);
        } catch (BadLocationException ex2) {
            JOptionPane.showMessageDialog(this, ex2.getMessage(), "Error de pintado", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de apertura archivo", JOptionPane.ERROR_MESSAGE);
        }

    }

    //Metodo que ayuda a poder tomar decisiones en el menu
    public boolean tomarDecision(String mensaje, String Titulo) {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                mensaje,
                Titulo,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        return opcion == JOptionPane.YES_OPTION;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblEdicionConfig = new javax.swing.JLabel();
        scrollErroresLog = new javax.swing.JScrollPane();
        textLogConfig = new javax.swing.JTextPane();
        btnGuardar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar Configuracion");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblEdicionConfig.setFont(new java.awt.Font("Liberation Serif", 1, 42)); // NOI18N
        lblEdicionConfig.setForeground(new java.awt.Color(83, 31, 11));
        lblEdicionConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdicionConfig.setText("Editar configuracion:");

        textLogConfig.setBackground(new java.awt.Color(228, 228, 228));
        textLogConfig.setFont(new java.awt.Font("Liberation Serif", 1, 20)); // NOI18N
        textLogConfig.setForeground(new java.awt.Color(140, 1, 25));
        textLogConfig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textLogConfigKeyReleased(evt);
            }
        });
        scrollErroresLog.setViewportView(textLogConfig);

        btnGuardar.setBackground(new java.awt.Color(46, 136, 80));
        btnGuardar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(223, 223, 223));
        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnReiniciar.setBackground(new java.awt.Color(136, 62, 45));
        btnReiniciar.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        btnReiniciar.setForeground(new java.awt.Color(223, 223, 223));
        btnReiniciar.setText("Reiniciar por defecto");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEdicionConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scrollErroresLog, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblEdicionConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollErroresLog, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textLogConfigKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLogConfigKeyReleased
        //Detecta cada vez que se hace un cambio

        int code = evt.getKeyCode();
        if (code == KeyEvent.VK_CONTROL || code == KeyEvent.VK_SHIFT
                || code == KeyEvent.VK_ALT
                || code == KeyEvent.VK_LEFT || code == KeyEvent.VK_RIGHT || code == KeyEvent.VK_UP || code == KeyEvent.VK_DOWN
                || code == KeyEvent.VK_TAB || code == KeyEvent.VK_CAPS_LOCK) {
            return;
        }

        if (this.textLogConfig.getText().isBlank()) {
            return;
        }

        this.hayCambio = true;
    }//GEN-LAST:event_textLogConfigKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Boton manual que permite analizar el texto
        if (this.textLogConfig.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "NO PUEDES BORRAR LA CONFIGURACION PREDETERMINADA\nCIERRE LA VENTANA", "CONFIG EN BLANCO", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (this.gestionLecturas.getDatosConfig().comprobarEntradas(this.textLogConfig.getText())) {
                this.gestionLecturas.getDatosConfig().guardarCambios();
                this.gestionLecturas.getDatosConfig().cargarDesdeJson();
                this.gestionLecturas.analizarEntradas(paneLogAnalisis, paneLogErrores);
                this.hayCambio = false;
            }

        } catch (ErrorEncontradoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Formato incorrecto", JOptionPane.ERROR_MESSAGE);
        } catch (ErrorPuntualException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de guardado", JOptionPane.ERROR_MESSAGE);
        } catch (ConfigException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de carga de configuracion", JOptionPane.ERROR_MESSAGE);
        } catch (BadLocationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de pintado", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de apertura archivo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Se pregunta si se desea cerrar el dialog

        if (this.hayCambio) {

            if (tomarDecision("No has guardado cambios. \nDeseas descartarlos?", "Descartar cambio")) {
                this.dispose();
            }
        }

        if (!this.hayCambio) {
            this.dispose();
        }


    }//GEN-LAST:event_formWindowClosing

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed

        try {

            this.gestionLecturas.getDatosConfig().reiniciarPredeterminado(this.textLogConfig);
            if (this.gestionLecturas.getDatosConfig().comprobarEntradas(this.textLogConfig.getText())) {

                this.gestionLecturas.getDatosConfig().guardarCambios();
                this.gestionLecturas.getDatosConfig().cargarDesdeJson();
                this.gestionLecturas.analizarEntradas(paneLogAnalisis, paneLogErrores);

                this.hayCambio = false;

            }
        } catch (BadLocationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Formato de escritura incorrecto", JOptionPane.ERROR_MESSAGE);
        } catch (ConfigException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de carga de configuracion", JOptionPane.ERROR_MESSAGE);
        } catch (ErrorEncontradoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Formato incorrecto", JOptionPane.ERROR_MESSAGE);
        } catch (ErrorPuntualException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de guardado", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de apertura archivo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel lblEdicionConfig;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollErroresLog;
    private javax.swing.JTextPane textLogConfig;
    // End of variables declaration//GEN-END:variables
}
